<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.4 on win32)" generated="20191021 13:18:41.501" rpa="false">
<suite id="s1" name="Demo" source="C:\Users\vikgaur\PycharmProjects\ APITestingRobotFramework\demo.robot">
<test id="s1-t1" name="Open_Dialer">
<kw name="setup and open dialer">
<kw name="Open Application">
<arguments>
<arg>${Appium_server}</arg>
<arg>platformName=android</arg>
<arg>platformVersion=${platfrom}</arg>
<arg>deviceName=${Device_name}</arg>
<arg>automationName=${automationName}</arg>
<arg>appPackage=${appPackage}</arg>
<arg>newCommandTimeout=2500</arg>
<arg>appActivity=${appActivity}</arg>
</arguments>
<assign>
<var>${androiddriver}=</var>
</assign>
<msg timestamp="20191021 13:18:41.561" level="FAIL">No keyword with name 'Open Application' found.</msg>
<status status="FAIL" starttime="20191021 13:18:41.561" endtime="20191021 13:18:41.561"></status>
</kw>
<status status="FAIL" starttime="20191021 13:18:41.559" endtime="20191021 13:18:41.561"></status>
</kw>
<status status="FAIL" starttime="20191021 13:18:41.558" endtime="20191021 13:18:41.562" critical="yes">No keyword with name 'Open Application' found.</status>
</test>
<status status="FAIL" starttime="20191021 13:18:41.503" endtime="20191021 13:18:41.563"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Demo">Demo</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20191021 13:18:41.493" level="ERROR">Error in file 'C:\Users\vikgaur\PycharmProjects\ APITestingRobotFramework\demo.robot': Setting 'Documentation' used multiple times.</msg>
<msg timestamp="20191021 13:18:41.538" level="ERROR">Error in file 'C:\Users\vikgaur\PycharmProjects\ APITestingRobotFramework\demo.robot': Importing test library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python37\Scripts\robot.exe
  c:\python37\python37.zip
  c:\python37\DLLs
  c:\python37\lib
  c:\python37
  C:\Users\vikgaur\AppData\Roaming\Python\Python37\site-packages
  c:\python37\lib\site-packages</msg>
<msg timestamp="20191021 13:18:41.555" level="ERROR">Error in file 'C:\Users\vikgaur\PycharmProjects\ APITestingRobotFramework\demo.robot': Importing test library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python37\Scripts\robot.exe
  c:\python37\python37.zip
  c:\python37\DLLs
  c:\python37\lib
  c:\python37
  C:\Users\vikgaur\AppData\Roaming\Python\Python37\site-packages
  c:\python37\lib\site-packages</msg>
</errors>
</robot>
